### ISSUE TITLE
Where's the Button?

### ISSUE THREAD

**Issue by TechyDesignGal** [baz1/DesmosToSVG#1]
I've installed and enabled Grease Monkey.  I've installed the DesmostoSVG script.  There's a GreaseMonkey icon in a toolbar at the top of Firefox.  When I navigate to https://www.desmos.com/calculator the last item in the GreaseMonkey menu changes from "no installed scripts on this page" to "DesmosToSVG" with a check mark to the left.  But I can't seem to find the "Get SVG" button.  TIA

**Comment by baz1** [comment]
Hello TechyDesignGal,
Thank you for your message.
It may be that the website has changed since I wrote this script.
I will take a look and update it this weekend.
Remi

**Comment by TechyDesignGal** [comment]
Thank you!  Much appreciated.  I'm doing a workshop for high school girls on how designers use math in fashion and it would be really helpful to save our graph designs as SVG.

**Comment by baz1** [comment]
Hi TechyDesignGal,
I just committed a slight change that should do the trick.
Please come back to me if you have any further issue.
