### ISSUE TITLE
doesnt work on firefox or chrome 

### ISSUE THREAD

**Issue by GMW247** [baz1/DesmosToSVG#2]
i have tried it on both chrome and firefox and it doesn't currently work on either. i installed the script into Greasemonkey and i see no save button.

**Comment by etheory** [comment]
If you open a new tab and reload desmos from scratch with the script enabled, I think the button will appear for you. It certainly does for me. It doesn't matter though, as it still doesn't seem to work. The button for me is blanked out and I can't click on it: 
![image](https://user-images.githubusercontent.com/1401669/40792198-b037b3c4-653c-11e8-9669-e0f93f336efc.png)

I am using Greasemonkey 4.4.0 with Firefox Quantum 60.0.1 (64-bit)
Dragging the view as described in the docs doesn't enable the button either.

**Comment by baz1** [comment]
Hi,
I believe the script stopped working because of an update of GreaseMonkey.
I just updated the script; please retry with the updated version.
Thanks

Remi
