### ISSUE TITLE
Desmos Canvas disappears

### ISSUE THREAD

**Issue by sambtalcott** [baz1/DesmosToSVG#5]
This was working great until today - now whenever the code is running the Desmos canvas disappears. I can still add equations but nothing displays. Clicking the Export button creates a blank .svg file.

Tested on Firefox with GreaseMonkey and Chrome with TamperMonkey.

**Comment by sambtalcott** [comment]
Don't really know what I'm doing but tried to debug since I need this working for a class project this week. I found that commenting out the "set:" function under DesmosToSVG.ctxHandler stopped the crash from happening. It also does weird things to the gridlines and axes, but I'm not using those anyway.

**Comment by baz1** [comment]
Hi,
Happy to hear that this project is useful :-)
I just added a small missing "return true;" line (required not to get a TypeError according to https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy/handler/set) which seems to fix this issue.
Please confirm on your side, and close the issue if it is indeed resolved.
Thank you

**Comment by sambtalcott** [comment]
It works! Thanks so much (and thanks for fixing it so quickly!). This has been super useful - I'm a high school math teacher and we're using it for a project where students create a design in Desmos for a piece of art or jewelry and then laser cut it into a physical object. The whole project wouldn't be possible without this code!
