### ISSUE TITLE
Graph interface goes white when equation is inputted

### ISSUE THREAD

**Issue by foci00** [baz1/DesmosToSVG#6]
Does not work anymore, outputs a white svg file.

**Comment by baz1** [comment]
The current version seems to work on my side.
I believe this is probably the same as https://github.com/baz1/DesmosToSVG/issues/5 ; could you make sure that you are running the latest version of this code, and if not, that the current version works on your side?
Thank you

**Comment by foci00** [comment]
It works, thanks for the feedback😊 This has been super useful for my assignments thank you so much
